name = "cb-butchers-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
TEAM_NAME = "CB BUTchers"
# Po nasazeni dopln napr. "https://uzivatel.github.io,http://localhost:8000"
ALLOWED_ORIGINS = "http://localhost:3000,http://10.0.1.16:3000,https://curlingcalendar.adamdaliborj.workers.dev/"

[[d1_databases]]
binding = "cb_butchers_calendar"
database_name = "cb-butchers-calendar"
database_id = "1e7c2c4e-edd3-4f79-ad27-20b9c8e602b3"
